index index.html;

# Deny all attempts to access hidden files such as .htaccess or .htpasswd.
location ~ /\. {
    deny all;
}

location / {
    try_files $uri $uri/ /index.html;
}

client_max_body_size 20m;
